template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

redis:
  hostname: pub-redis-13946.us-east-1-4.2.ec2.garantiadata.com
  port: 13946